export { GET_MESSAGE_QUERY } from './queries';
export {
	LOGIN_USER_MUTATION,
	CREATE_USER_MUTATION,
	CREATE_MSG_MUTATION,
	DELETE_MSG_MUTATION,
	UPLOAD_FILE_MUTATION,
	CREATE_FRIEND_MUTATION,
} from './mutations';
export { MSG_SUBSCRIPTION, FILE_SUBSCRIPTION, FRIEND_SUBSCRIPTION } from './subscription';
